language: csharp

sudo: false  # use the new container-based Travis infrastructure
dist: trusty
dotnet: 2.1.4

before_script:
  - nvm install --lts
  - nvm use --lts

cache:
  yarn: true

script:
  - ./build.sh build
